#project/ital/settings/base.py
"""
Django settings for ital project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from importlib.util import find_spec
from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


SECRET_KEY = config("SECRET_KEY")


def env_bool(name: str, default: bool = False) -> bool:
    raw = config(name, default=None)
    if raw is None:
        return default
    value = str(raw).strip().lower()
    if value in {"1", "true", "yes", "on"}:
        return True
    if value in {"0", "false", "no", "off", "release", "prod", "production"}:
        return False
    return default


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", default=False)


def _csv_list(name: str, default: str = "") -> list[str]:
    raw = config(name, default=default)
    return [item.strip() for item in raw.split(",") if item.strip()]


ALLOWED_HOSTS = _csv_list("ALLOWED_HOSTS", default="localhost,127.0.0.1")
CSRF_TRUSTED_ORIGINS = _csv_list("CSRF_TRUSTED_ORIGINS")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "config.users.apps.UsersConfig",
    "apps.accounts.apps.AccountsConfig",
    "apps.csm.apps.CsmConfig",
    "apps.cart.apps.CartConfig",
    "apps.orders.apps.OrdersConfig",
    "apps.shipping.apps.ShippingConfig",
    "apps.catalog",
    "apps.products",
    "apps.seo",
]

# Use Jazzmin admin skin only when dependency is installed.
if find_spec("jazzmin") is not None:
    INSTALLED_APPS.insert(0, "jazzmin")

SITE_ID = 1
AUTH_USER_MODEL = "users.CustomUser"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ital.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.csm.context_processors.ui_context",
            ],
        },
    },
]

WSGI_APPLICATION = "ital.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("POSTGRES_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT", cast=int),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = config("LANGUAGE_CODE", default="en-us")

TIME_ZONE = config("TIME_ZONE", default="UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = config("STATIC_URL", default="/static/")
STATIC_ROOT = BASE_DIR / "staticfiles"


USE_S3_MEDIA = env_bool("USE_S3_MEDIA", default=False)
MEDIA_STORAGE_BACKEND = "django.core.files.storage.FileSystemStorage"
MEDIA_STORAGE_OPTIONS: dict = {}

if USE_S3_MEDIA:
    if "storages" not in INSTALLED_APPS:
        INSTALLED_APPS.append("storages")

    AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = config("AWS_S3_REGION_NAME", default="")
    AWS_S3_ENDPOINT_URL = config("AWS_S3_ENDPOINT_URL", default="")
    AWS_S3_CUSTOM_DOMAIN = config("AWS_S3_CUSTOM_DOMAIN", default="")
    AWS_S3_ADDRESSING_STYLE = config("AWS_S3_ADDRESSING_STYLE", default="auto")
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = env_bool("AWS_QUERYSTRING_AUTH", default=False)
    AWS_S3_FILE_OVERWRITE = env_bool("AWS_S3_FILE_OVERWRITE", default=False)
    AWS_MEDIA_LOCATION = config("AWS_MEDIA_LOCATION", default="media")

    MEDIA_STORAGE_BACKEND = "storages.backends.s3.S3Storage"
    MEDIA_STORAGE_OPTIONS = {
        "access_key": AWS_ACCESS_KEY_ID,
        "secret_key": AWS_SECRET_ACCESS_KEY,
        "bucket_name": AWS_STORAGE_BUCKET_NAME,
        "region_name": AWS_S3_REGION_NAME or None,
        "endpoint_url": AWS_S3_ENDPOINT_URL or None,
        "custom_domain": AWS_S3_CUSTOM_DOMAIN or None,
        "default_acl": None,
        "querystring_auth": AWS_QUERYSTRING_AUTH,
        "file_overwrite": AWS_S3_FILE_OVERWRITE,
        "location": AWS_MEDIA_LOCATION,
    }

    if AWS_S3_CUSTOM_DOMAIN:
        default_media_url = f"https://{AWS_S3_CUSTOM_DOMAIN.rstrip('/')}/{AWS_MEDIA_LOCATION.strip('/')}/"
    elif AWS_S3_ENDPOINT_URL:
        default_media_url = (
            f"{AWS_S3_ENDPOINT_URL.rstrip('/')}/{AWS_STORAGE_BUCKET_NAME}/{AWS_MEDIA_LOCATION.strip('/')}/"
        )
    else:
        default_media_url = f"/{AWS_MEDIA_LOCATION.strip('/')}/"

    MEDIA_URL = config("MEDIA_URL", default=default_media_url)
    STORAGES = {
        "default": {
            "BACKEND": MEDIA_STORAGE_BACKEND,
            "OPTIONS": MEDIA_STORAGE_OPTIONS,
        },
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }
else:
    MEDIA_URL = config("MEDIA_URL", default="/media/")
    MEDIA_ROOT = BASE_DIR / "media"

CONTACT_SEND_ENABLED = env_bool("CONTACT_SEND_ENABLED", default=False)

STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY", default="")
STRIPE_PUBLISHABLE_KEY = config("STRIPE_PUBLISHABLE_KEY", default="")
STRIPE_WEBHOOK_SECRET = config("STRIPE_WEBHOOK_SECRET", default="")
ORDER_ACCESS_TOKEN_MAX_AGE = config("ORDER_ACCESS_TOKEN_MAX_AGE", default=7200, cast=int)
LOGIN_URL = "/account/login/"
LOGIN_REDIRECT_URL = "/account/"
