# Generated by Django 6.0 on 2026-03-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_returnpolicyconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnpolicyconfig',
            options={'ordering': ['-is_active', 'name', 'id'], 'verbose_name': 'Konfigurácia pravidiel vrátenia', 'verbose_name_plural': 'Konfigurácie pravidiel vrátenia'},
        ),
        migrations.AlterModelOptions(
            name='shippingproviderconfig',
            options={'ordering': ['provider'], 'verbose_name': 'Konfigurácia poskytovateľa dopravy', 'verbose_name_plural': 'Konfigurácie poskytovateľov dopravy'},
        ),
        migrations.AlterField(
            model_name='returnpolicyconfig',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené'),
        ),
        migrations.AlterField(
            model_name='returnpolicyconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktívna'),
        ),
        migrations.AlterField(
            model_name='returnpolicyconfig',
            name='name',
            field=models.CharField(default='Predvolená politika', max_length=120, verbose_name='Názov'),
        ),
        migrations.AlterField(
            model_name='returnpolicyconfig',
            name='return_window_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Počet dní na vrátenie'),
        ),
        migrations.AlterField(
            model_name='returnpolicyconfig',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualizované'),
        ),
        migrations.AlterField(
            model_name='shippingproviderconfig',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='API kľúč'),
        ),
        migrations.AlterField(
            model_name='shippingproviderconfig',
            name='api_secret',
            field=models.CharField(blank=True, max_length=255, verbose_name='API tajomstvo'),
        ),
        migrations.AlterField(
            model_name='shippingproviderconfig',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené'),
        ),
        migrations.AlterField(
            model_name='shippingproviderconfig',
            name='delivery_eta_label',
            field=models.CharField(blank=True, max_length=120, verbose_name='Text doručenia'),
        ),
        migrations.AlterField(
            model_name='shippingproviderconfig',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aktívny'),
        ),
        migrations.AlterField(
            model_name='shippingproviderconfig',
            name='provider',
            field=models.CharField(choices=[('paketa', 'Paketa'), ('dpd', 'DPD')], max_length=20, unique=True, verbose_name='Poskytovateľ'),
        ),
        migrations.AlterField(
            model_name='shippingproviderconfig',
            name='sandbox_mode',
            field=models.BooleanField(default=True, verbose_name='Sandbox režim'),
        ),
        migrations.AlterField(
            model_name='shippingproviderconfig',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualizované'),
        ),
        migrations.AlterField(
            model_name='shippingproviderconfig',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=255, verbose_name='Webhook tajomstvo'),
        ),
    ]
