# Generated by Django 6.0 on 2026-03-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0001_contact_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kontaktná správa', 'verbose_name_plural': 'Kontaktné správy'},
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='consent_given',
            field=models.BooleanField(default=False, verbose_name='Súhlas udelený'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Súhlas udelený dňa'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Spracované'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Správa'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='messenger_handle',
            field=models.CharField(max_length=120, verbose_name='Kontakt na messenger'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='messenger_type',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('signal', 'Signal'), ('other', 'Iné')], max_length=40, verbose_name='Typ messengera'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Meno'),
        ),
    ]
