# Generated by Django 6.0 on 2026-03-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0002_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Ricotti', max_length=120, verbose_name='Názov stránky')),
                ('logo_alt', models.CharField(blank=True, max_length=160, verbose_name='Alternatívny text loga')),
                ('logo_original', models.ImageField(blank=True, null=True, upload_to='branding/original/', verbose_name='Pôvodné logo')),
                ('logo_header', models.ImageField(blank=True, editable=False, null=True, upload_to='branding/header/', verbose_name='Logo pre hlavičku')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizované')),
            ],
            options={
                'verbose_name': 'Branding stránky',
                'verbose_name_plural': 'Branding stránky',
            },
        ),
    ]
