# Generated by Django 6.0 on 2026-03-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csm', '0007_homehero_links'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Legacy kontaktná správa', 'verbose_name_plural': 'Legacy kontaktné správy'},
        ),
    ]
