# Generated by Django 6.0 on 2026-02-18 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cart',
            new_name='cart_cart_user_id_5d777a_idx',
            old_name='cart_user_i_9f8f15_idx',
        ),
        migrations.RenameIndex(
            model_name='cart',
            new_name='cart_cart_session_3c25be_idx',
            old_name='cart_sessi_9e0f37_idx',
        ),
        migrations.RenameIndex(
            model_name='cartitem',
            new_name='cart_cartit_cart_id_4bd8c3_idx',
            old_name='cart_cart_p_2b2f93_idx',
        ),
    ]
