# Generated by Django 6.0 on 2026-02-24 00:00

import django.db.models.deletion
from django.db import migrations, models
import uuid


def forwards_fill_variant(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        table_description = connection.introspection.get_table_description(cursor, "products_productvariant")
        variant_columns = {col.name for col in table_description}
        has_public_id = "public_id" in variant_columns

        cursor.execute(
            """
            SELECT ci.id, ci.product_id, p.price, p.compare_at, p.is_active
            FROM cart_cartitem ci
            JOIN products_product p ON p.id = ci.product_id
            WHERE ci.variant_id IS NULL
            """
        )
        rows = cursor.fetchall()

        for cartitem_id, product_id, price, compare_at, is_active in rows:
            cursor.execute(
                """
                SELECT id
                FROM products_productvariant
                WHERE product_id = %s AND size = %s AND color = %s
                LIMIT 1
                """,
                [product_id, "UNI", "Default"],
            )
            existing = cursor.fetchone()
            if existing:
                variant_id = existing[0]
            else:
                sku = f"LEGACY-{product_id}-{uuid.uuid4().hex[:8]}"
                if has_public_id:
                    cursor.execute(
                        """
                        INSERT INTO products_productvariant
                        (public_id, product_id, size, color, sku, price, compare_at, stock, is_active, created, updated)
                        VALUES (%s, %s, %s, %s, %s, %s, %s, 0, %s, NOW(), NOW())
                        RETURNING id
                        """,
                        [str(uuid.uuid4()), product_id, "UNI", "Default", sku, price, compare_at, is_active],
                    )
                else:
                    cursor.execute(
                        """
                        INSERT INTO products_productvariant
                        (product_id, size, color, sku, price, compare_at, stock, is_active, created, updated)
                        VALUES (%s, %s, %s, %s, %s, %s, 0, %s, NOW(), NOW())
                        RETURNING id
                        """,
                        [product_id, "UNI", "Default", sku, price, compare_at, is_active],
                    )
                variant_id = cursor.fetchone()[0]

            cursor.execute(
                "UPDATE cart_cartitem SET variant_id = %s WHERE id = %s",
                [variant_id, cartitem_id],
            )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("products", "0012_repair_productvariant_public_id"),
        ("cart", "0002_rename_cart_user_i_9f8f15_idx_cart_cart_user_id_5d777a_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="variant",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="products.productvariant"),
        ),
        migrations.RunPython(forwards_fill_variant, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="cartitem",
            name="variant",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="products.productvariant"),
        ),
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="uniq_cart_product",
        ),
        migrations.RemoveIndex(
            model_name="cartitem",
            name="cart_cartit_cart_id_4bd8c3_idx",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(fields=("cart", "variant"), name="uniq_cart_variant"),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["cart", "variant"], name="cart_cartit_cart_id_8609d3_idx"),
        ),
    ]
