# Generated by Django 6.0 on 2026-03-16 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_variant'),
        ('products', '0017_alter_category_cover_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Košík', 'verbose_name_plural': 'Košíky'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Položka košíka', 'verbose_name_plural': 'Položky košíka'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktívny'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Kľúč relácie'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualizované'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Používateľ'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart', verbose_name='Košík'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Množstvo'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualizované'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productvariant', verbose_name='Variant'),
        ),
    ]
