# Generated by Django 6.0 on 2026-02-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_status_5a4cbe_idx',
            old_name='orders_orde_status__9f83f9_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_user_id_1a56cf_idx',
            old_name='orders_orde_user_id_b9c104_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='orders_orde_order_i_52f79a_idx',
            old_name='orders_orde_order_i_2fa7f2_idx',
        ),
    ]
