# Generated by Django 6.0 on 2026-02-24 00:00

import django.db.models.deletion
from django.db import migrations, models
import uuid


def forwards_fill_orderitem_variant(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        table_description = connection.introspection.get_table_description(cursor, "products_productvariant")
        variant_columns = {col.name for col in table_description}
        has_public_id = "public_id" in variant_columns

        cursor.execute(
            """
            SELECT oi.id, oi.product_id, oi.unit_price, p.name
            FROM orders_orderitem oi
            JOIN products_product p ON p.id = oi.product_id
            WHERE oi.variant_id IS NULL
            """
        )
        rows = cursor.fetchall()

        for orderitem_id, product_id, unit_price, product_name in rows:
            cursor.execute(
                """
                SELECT id, sku, size, color
                FROM products_productvariant
                WHERE product_id = %s AND size = %s AND color = %s
                LIMIT 1
                """,
                [product_id, "UNI", "Default"],
            )
            existing = cursor.fetchone()
            if existing:
                variant_id, sku, size, color = existing
            else:
                sku = f"LEGACY-{product_id}-{uuid.uuid4().hex[:8]}"
                if has_public_id:
                    cursor.execute(
                        """
                        INSERT INTO products_productvariant
                        (public_id, product_id, size, color, sku, price, compare_at, stock, is_active, created, updated)
                        VALUES (%s, %s, %s, %s, %s, %s, NULL, 0, TRUE, NOW(), NOW())
                        RETURNING id, size, color
                        """,
                        [str(uuid.uuid4()), product_id, "UNI", "Default", sku, unit_price],
                    )
                else:
                    cursor.execute(
                        """
                        INSERT INTO products_productvariant
                        (product_id, size, color, sku, price, compare_at, stock, is_active, created, updated)
                        VALUES (%s, %s, %s, %s, %s, NULL, 0, TRUE, NOW(), NOW())
                        RETURNING id, size, color
                        """,
                        [product_id, "UNI", "Default", sku, unit_price],
                    )
                variant_id, size, color = cursor.fetchone()

            cursor.execute(
                """
                UPDATE orders_orderitem
                SET variant_id = %s, product_name = %s, sku = %s, size = %s, color = %s
                WHERE id = %s
                """,
                [variant_id, product_name, sku, size, color, orderitem_id],
            )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("products", "0012_repair_productvariant_public_id"),
        ("orders", "0002_rename_orders_orde_status__9f83f9_idx_orders_orde_status_5a4cbe_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="color",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="size",
            field=models.CharField(default="", max_length=32),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="sku",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="products.productvariant"),
        ),
        migrations.RunPython(forwards_fill_orderitem_variant, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="products.productvariant"),
        ),
        migrations.RemoveConstraint(
            model_name="orderitem",
            name="uniq_order_product",
        ),
        migrations.RemoveIndex(
            model_name="orderitem",
            name="orders_orde_order_i_52f79a_idx",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(fields=("order", "variant"), name="uniq_order_variant"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["order", "variant"], name="orders_orde_order_i_c8de3b_idx"),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(choices=[("gopay", "GoPay")], default="gopay", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("external_id", models.CharField(blank=True, max_length=64)),
                ("gateway_url", models.URLField(blank=True)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="orders.order"),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["provider", "status"], name="orders_paym_provide_8b8f0a_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["external_id"], name="orders_paym_externa_549d50_idx"),
        ),
    ]
