# Generated by Django 6.0 on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderitem_variant_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(choices=[("stripe", "Stripe")], default="stripe", max_length=20),
        ),
    ]
