# Generated by Django 6.0 on 2026-03-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_payment_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
