# Generated by Django 6.0 on 2026-03-11 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_payment_gateway_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('canceled', 'Canceled')], max_length=20)),
                ('source', models.CharField(default='system', max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_events', to='orders.order')),
            ],
            options={
                'ordering': ['-created', '-id'],
                'indexes': [models.Index(fields=['order', 'created'], name='orders_orde_order_i_9d89cf_idx'), models.Index(fields=['status', 'created'], name='orders_orde_status_c957de_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled')], max_length=20)),
                ('source', models.CharField(default='system', max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_events', to='orders.payment')),
            ],
            options={
                'ordering': ['-created', '-id'],
                'indexes': [models.Index(fields=['payment', 'created'], name='orders_paym_payment_a97c4d_idx'), models.Index(fields=['status', 'created'], name='orders_paym_status_f52ca0_idx')],
            },
        ),
    ]
