# Generated by Django 6.0 on 2026-03-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderstatusevent_paymentstatusevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('paketa_pickup', 'Paketa pickup point'), ('dpd_home', 'DPD home delivery'), ('dpd_express', 'DPD express')], default='dpd_home', max_length=30),
        ),
    ]
