# Generated by Django 6.0 on 2026-03-16 15:47

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_shipping_method'),
        ('products', '0017_alter_category_cover_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-created'], 'verbose_name': 'Adresa', 'verbose_name_plural': 'Adresy'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'Objednávka', 'verbose_name_plural': 'Objednávky'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Položka objednávky', 'verbose_name_plural': 'Položky objednávky'},
        ),
        migrations.AlterModelOptions(
            name='orderstatusevent',
            options={'ordering': ['-created', '-id'], 'verbose_name': 'Udalosť stavu objednávky', 'verbose_name_plural': 'Udalosti stavu objednávky'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created'], 'verbose_name': 'Platba', 'verbose_name_plural': 'Platby'},
        ),
        migrations.AlterModelOptions(
            name='paymentstatusevent',
            options={'ordering': ['-created', '-id'], 'verbose_name': 'Udalosť stavu platby', 'verbose_name_plural': 'Udalosti stavu platby'},
        ),
        migrations.AlterModelOptions(
            name='processedstripeevent',
            options={'ordering': ['-created'], 'verbose_name': 'Spracovaná Stripe udalosť', 'verbose_name_plural': 'Spracované Stripe udalosti'},
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line1',
            field=models.CharField(max_length=255, verbose_name='Adresa, riadok 1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresa, riadok 2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=120, verbose_name='Mesto'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=2, verbose_name='Krajina'),
        ),
        migrations.AlterField(
            model_name='address',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené'),
        ),
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='address',
            name='full_name',
            field=models.CharField(max_length=120, verbose_name='Meno a priezvisko'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Telefón'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='PSČ'),
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(blank=True, max_length=120, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualizované'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Používateľ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Mena'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='order',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Verejné ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.address', verbose_name='Dodacia adresa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cena dopravy'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('paketa_pickup', 'Výdajné miesto Paketa'), ('dpd_home', 'Doručenie DPD na adresu'), ('dpd_express', 'DPD expres')], default='dpd_home', max_length=30, verbose_name='Spôsob dopravy'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Čaká sa'), ('paid', 'Zaplatené'), ('shipped', 'Odoslané'), ('canceled', 'Zrušené')], default='pending', max_length=20, verbose_name='Stav'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Medzisúčet'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Celkom'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualizované'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Používateľ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='color',
            field=models.CharField(default='', max_length=64, verbose_name='Farba'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena spolu'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Objednávka'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(default='', max_length=255, verbose_name='Názov produktu'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Množstvo'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='', max_length=32, verbose_name='Veľkosť'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sku',
            field=models.CharField(default='', max_length=64, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jednotková cena'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productvariant', verbose_name='Variant'),
        ),
        migrations.AlterField(
            model_name='orderstatusevent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené'),
        ),
        migrations.AlterField(
            model_name='orderstatusevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_events', to='orders.order', verbose_name='Objednávka'),
        ),
        migrations.AlterField(
            model_name='orderstatusevent',
            name='source',
            field=models.CharField(default='system', max_length=64, verbose_name='Zdroj'),
        ),
        migrations.AlterField(
            model_name='orderstatusevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Čaká sa'), ('paid', 'Zaplatené'), ('shipped', 'Odoslané'), ('canceled', 'Zrušené')], max_length=20, verbose_name='Stav'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Suma'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Mena'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Externé ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='URL platobnej brány'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Objednávka'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe')], default='stripe', max_length=20, verbose_name='Poskytovateľ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='raw_response',
            field=models.JSONField(blank=True, default=dict, verbose_name='Surová odpoveď'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'Vytvorené'), ('pending', 'Čaká sa'), ('paid', 'Zaplatené'), ('failed', 'Zlyhalo'), ('canceled', 'Zrušené')], default='created', max_length=20, verbose_name='Stav'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualizované'),
        ),
        migrations.AlterField(
            model_name='paymentstatusevent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené'),
        ),
        migrations.AlterField(
            model_name='paymentstatusevent',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_events', to='orders.payment', verbose_name='Platba'),
        ),
        migrations.AlterField(
            model_name='paymentstatusevent',
            name='source',
            field=models.CharField(default='system', max_length=64, verbose_name='Zdroj'),
        ),
        migrations.AlterField(
            model_name='paymentstatusevent',
            name='status',
            field=models.CharField(choices=[('created', 'Vytvorené'), ('pending', 'Čaká sa'), ('paid', 'Zaplatené'), ('failed', 'Zlyhalo'), ('canceled', 'Zrušené')], max_length=20, verbose_name='Stav'),
        ),
        migrations.AlterField(
            model_name='processedstripeevent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené'),
        ),
        migrations.AlterField(
            model_name='processedstripeevent',
            name='event_type',
            field=models.CharField(blank=True, max_length=120, verbose_name='Typ udalosti'),
        ),
        migrations.AlterField(
            model_name='processedstripeevent',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Payload'),
        ),
        migrations.AlterField(
            model_name='processedstripeevent',
            name='stripe_event_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Stripe ID udalosti'),
        ),
    ]
