# Generated by Django 6.0 on 2026-03-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_alter_address_options_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="packeta_carrier_id",
            field=models.CharField(blank=True, max_length=64, verbose_name="ID dopravcu Paketa"),
        ),
        migrations.AddField(
            model_name="order",
            name="packeta_carrier_pickup_point_id",
            field=models.CharField(blank=True, max_length=64, verbose_name="ID pickup pointu dopravcu Paketa"),
        ),
        migrations.AddField(
            model_name="order",
            name="packeta_point_address",
            field=models.CharField(blank=True, max_length=255, verbose_name="Adresa výdajného miesta Paketa"),
        ),
        migrations.AddField(
            model_name="order",
            name="packeta_point_id",
            field=models.CharField(blank=True, max_length=64, verbose_name="ID výdajného miesta Paketa"),
        ),
        migrations.AddField(
            model_name="order",
            name="packeta_point_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Názov výdajného miesta Paketa"),
        ),
        migrations.AddField(
            model_name="order",
            name="packeta_point_raw",
            field=models.JSONField(blank=True, default=dict, verbose_name="Surové dáta výdajného miesta Paketa"),
        ),
    ]
