# Generated by Django 6.0 on 2026-03-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_comm', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inquiry',
            new_name='customer_co_status_8f794c_idx',
            old_name='customer_co_status_2b70bc_idx',
        ),
        migrations.RenameIndex(
            model_name='inquiry',
            new_name='customer_co_source_3af377_idx',
            old_name='customer_co_source_49a2ec_idx',
        ),
        migrations.RenameIndex(
            model_name='inquirychanneldelivery',
            new_name='customer_co_channel_b919e5_idx',
            old_name='customer_co_channel_b0d9de_idx',
        ),
        migrations.RenameIndex(
            model_name='inquirychanneldelivery',
            new_name='customer_co_inquiry_1b08f9_idx',
            old_name='customer_co_inquiry_6ecb54_idx',
        ),
        migrations.RenameIndex(
            model_name='inquiryevent',
            new_name='customer_co_event_t_472cf1_idx',
            old_name='customer_co_event_t_f1d8b9_idx',
        ),
        migrations.RenameIndex(
            model_name='inquiryevent',
            new_name='customer_co_inquiry_707273_idx',
            old_name='customer_co_inquiry_e8d40d_idx',
        ),
        migrations.RenameIndex(
            model_name='privacyrequest',
            new_name='customer_co_request_eddd33_idx',
            old_name='customer_co_request_56d8a8_idx',
        ),
        migrations.RenameIndex(
            model_name='privacyrequest',
            new_name='customer_co_request_60667e_idx',
            old_name='customer_co_request_5f7a7f_idx',
        ),
    ]
