services:
  web:
    build:
      context: .
    environment:
      DJANGO_SETTINGS_MODULE: ital.settings.dev
    env_file:
      - ./.env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./media:/app/media
    depends_on:
      - db

  tailwind:
    build:
      context: .
    environment:
      DJANGO_SETTINGS_MODULE: ital.settings.dev
    command: python manage.py tailwind start
    volumes:
      - .:/app
    depends_on:
      - web

  db:
    image: postgres:15-alpine
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
