# Generated by Django 6.0 on 2026-01-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productimage_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productimage',
            name='products_pr_product_1b7905_idx',
        ),
        migrations.RemoveIndex(
            model_name='productimage',
            name='products_pr_product_f88290_idx',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='image_source_url',
            new_name='image_url',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
