# Generated by Django 6.0 on 2026-01-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productimage_products_pr_product_1b7905_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_file',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_card',
            field=models.ImageField(blank=True, null=True, upload_to='products/card/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_original',
            field=models.ImageField(blank=True, null=True, upload_to='products/original/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='products/thumb/'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_primary'], name='products_pr_product_1b7905_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'sort_order'], name='products_pr_product_f88290_idx'),
        ),
    ]
