# Generated by Django 6.0 on 2026-01-14 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_updated'),
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seo_meta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seo.seometa'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_meta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seo.seometa'),
        ),
    ]
