# Generated by Django 6.0 on 2026-02-12 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_seo_meta_product_seo_meta'),
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='seo_meta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seo.seometa'),
        ),
    ]
