# Generated by Django 6.0 on 2026-02-24 00:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_category_seo_meta"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("size", models.CharField(max_length=32)),
                ("color", models.CharField(max_length=64)),
                ("sku", models.CharField(max_length=64, unique=True)),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("compare_at", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="variants", to="products.product")),
            ],
            options={
                "ordering": ["product", "id"],
            },
        ),
        migrations.CreateModel(
            name="VariantImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image_original", models.ImageField(blank=True, null=True, upload_to="products/variants/original/")),
                ("image_card", models.ImageField(blank=True, null=True, upload_to="products/variants/card/")),
                ("image_thumb", models.ImageField(blank=True, null=True, upload_to="products/variants/thumb/")),
                ("alt", models.CharField(blank=True, max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("variant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="products.productvariant")),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["product", "is_active"], name="products_pr_product_e1f6f5_idx"),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(fields=("product", "size", "color"), name="uniq_variant_size_color"),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["sku"], name="products_pr_sku_54d3f7_idx"),
        ),
        migrations.AddIndex(
            model_name="variantimage",
            index=models.Index(fields=["variant", "is_primary"], name="products_va_variant_b27a7a_idx"),
        ),
        migrations.AddIndex(
            model_name="variantimage",
            index=models.Index(fields=["variant", "sort_order"], name="products_va_variant_4f5f7b_idx"),
        ),
    ]
