# Generated by Django 6.0 on 2026-02-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_variant_and_image'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='products_pr_product_66459e_idx',
            old_name='products_pr_product_e1f6f5_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='products_pr_sku_dcab68_idx',
            old_name='products_pr_sku_54d3f7_idx',
        ),
        migrations.RenameIndex(
            model_name='variantimage',
            new_name='products_va_variant_726b1f_idx',
            old_name='products_va_variant_b27a7a_idx',
        ),
        migrations.RenameIndex(
            model_name='variantimage',
            new_name='products_va_variant_20bafb_idx',
            old_name='products_va_variant_4f5f7b_idx',
        ),
    ]
