# Generated by Django 6.0 on 2026-03-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_origin_country_product_details'),
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created', '-id']},
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='products_pr_product_66459e_idx',
        ),
        migrations.AddField(
            model_name='category',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_covers/', verbose_name='Cover image'),
        ),
        migrations.AddField(
            model_name='category',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', verbose_name='External cover image URL'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-created'], name='products_pr_is_acti_05a802_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'brand'], name='products_pr_is_acti_146409_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_trending', '-created'], name='products_pr_is_tren_75dffb_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='products_pr_brand_4bfaa4_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active', 'price'], name='products_pr_product_bbf65c_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active', 'stock'], name='products_pr_product_4c510c_idx'),
        ),
    ]
