# Generated by Django 6.0 on 2026-03-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_covers/', verbose_name='Titulný obrázok'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', verbose_name='Externá URL titulného obrázka'),
        ),
    ]
