# Generated by Django 6.0 on 2026-03-16 15:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seometa',
            options={'verbose_name': 'SEO meta', 'verbose_name_plural': 'SEO meta'},
        ),
        migrations.AlterField(
            model_name='seometa',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vytvorené'),
        ),
        migrations.AlterField(
            model_name='seometa',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='seometa',
            name='keywords',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Kľúčové slová'),
        ),
        migrations.AlterField(
            model_name='seometa',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/og_images/', verbose_name='OG obrázok'),
        ),
        migrations.AlterField(
            model_name='seometa',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Verejné ID'),
        ),
        migrations.AlterField(
            model_name='seometa',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titulok'),
        ),
        migrations.AlterField(
            model_name='seometa',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualizované'),
        ),
    ]
