# Generated by Django 6.0 on 2026-03-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppLogEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Vytvorené")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "DEBUG"),
                            ("INFO", "INFO"),
                            ("WARNING", "WARNING"),
                            ("ERROR", "ERROR"),
                            ("CRITICAL", "CRITICAL"),
                        ],
                        max_length=16,
                        verbose_name="Úroveň",
                    ),
                ),
                ("logger_name", models.CharField(max_length=255, verbose_name="Logger")),
                ("event_type", models.CharField(blank=True, max_length=255, verbose_name="Typ udalosti")),
                ("message", models.TextField(verbose_name="Správa")),
                ("request_id", models.CharField(blank=True, max_length=64, verbose_name="Request ID")),
                ("request_method", models.CharField(blank=True, max_length=16, verbose_name="HTTP metóda")),
                ("request_path", models.CharField(blank=True, max_length=1024, verbose_name="Request path")),
                ("remote_addr", models.CharField(blank=True, max_length=64, verbose_name="IP adresa")),
                ("payload", models.JSONField(blank=True, default=dict, verbose_name="Doplňujúce dáta")),
                ("exception", models.TextField(blank=True, verbose_name="Výnimka")),
            ],
            options={
                "verbose_name": "Aplikačný log",
                "verbose_name_plural": "Aplikačné logy",
                "ordering": ["-created", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="applogentry",
            index=models.Index(fields=["level", "created"], name="ops_apploge_level_5dc6a6_idx"),
        ),
        migrations.AddIndex(
            model_name="applogentry",
            index=models.Index(fields=["logger_name", "created"], name="ops_apploge_logger__92f06b_idx"),
        ),
        migrations.AddIndex(
            model_name="applogentry",
            index=models.Index(fields=["event_type", "created"], name="ops_apploge_event_t_9d3f52_idx"),
        ),
        migrations.AddIndex(
            model_name="applogentry",
            index=models.Index(fields=["request_id", "created"], name="ops_apploge_request_5d8382_idx"),
        ),
    ]
