# Generated by Django 6.0 on 2026-03-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='applogentry',
            new_name='ops_apploge_level_83a2a1_idx',
            old_name='ops_apploge_level_5dc6a6_idx',
        ),
        migrations.RenameIndex(
            model_name='applogentry',
            new_name='ops_apploge_logger__b0eb0b_idx',
            old_name='ops_apploge_logger__92f06b_idx',
        ),
        migrations.RenameIndex(
            model_name='applogentry',
            new_name='ops_apploge_event_t_3345bc_idx',
            old_name='ops_apploge_event_t_9d3f52_idx',
        ),
        migrations.RenameIndex(
            model_name='applogentry',
            new_name='ops_apploge_request_c1daec_idx',
            old_name='ops_apploge_request_5d8382_idx',
        ),
    ]
